[package]
name = "libc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustrt = {path = "procmacro"}
elf = { version = "0.7.2", default-features = false}
rtl = {path = "../../rtl" }

[lib]
name = "libc"
