name = "Console app"
board = 'qemu'

[[component]]
name = "nameserver"
implements = ["nameserver", "init"]

[[component]]
name = "uart"
implements = ["serial"]
depends = ["nameserver"]

[[component]]
name = "console"
depends = ["nameserver", "serial"]
