[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
simplelog = "0.12.2"
toml = "0.9.5"
