[env]
TARGET = "aarch64-unknown-none-softfloat"
RUSTFLAGS = "-C link-arg=--library-path=. -C link-arg=--script=aarch64-qemu.ld -C force-frame-pointers"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
env = { "RUSTFLAGS" = "${RUSTFLAGS}" }
command = "cargo"
args = ["build", "--target=${TARGET}"]

[tasks.my-flow]
dependencies = [
    "format",
    "build"
]
