[target.'cfg(target_os = "none")']
runner = "qemu-system-aarch64 -machine virt,gic-version=2 -m 2048M -cpu cortex-a53 -smp 2 -nographic -kernel "

[target.aarch64-unknown-none-softfloat]
rustflags = [
	"-C", "link-arg=--script=src/kernel/src/arch/aarch64/aarch64-qemu.ld",
	"-C", "force-frame-pointers",
	"-C", "link-dead-code"
]
