[target.'cfg(target_os = "none")']
runner = "qemu-system-aarch64 -machine virt,gic-version=2 -m 2048M -cpu cortex-a53 -smp 2 -nographic -kernel "

[alias]
xtask = "run --package xtask --"

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true, force = true }

[build]
rustflags = [
	"-C", "force-frame-pointers",
]
