[env]
TARGET = "aarch64-unknown-none-softfloat"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--target=${TARGET}"]
dependencies = ["clean"]

[tasks.test]
command = "echo"

[tasks.my-flow]
dependencies = [
    "build"
]
